# fly.toml app configuration file generated for purple-mountain-5733 on 2023-06-08T05:43:28Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "purple-mountain-5733"
primary_region = "nrt"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[env]
  APP_URL = "https://purple-mountain-5733.fly.dev"
  APP_NAME = "TaskList"
  APP_DEBUG = false
  DB_CONNECTION = "pgsql"
  DB_HOST = "db.nesdkrdkreknidixuigp.supabase.co"
  DB_PORT = 5432
  DB_DATABASE = "postgres"
  DB_USERNAME = "postgres"
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
